### ISSUE TITLE
cannot reproduce your results

### ISSUE THREAD

**Issue by JeffC0628** [PlayVoice/Uni-SVC#15]
It's really a great job, but I cannot reproduce the result, it sounds not good, here is some information
![image](https://user-images.githubusercontent.com/24654967/223611488-b4131b45-4d0b-43ef-b0c6-57ef7ac0192a.png)

https://user-images.githubusercontent.com/24654967/223609715-001d551c-ef0f-4f73-9f58-28b8c2de37b3.mp4

https://user-images.githubusercontent.com/24654967/223609722-890dba1f-da34-45b4-bb1b-6c48e54350f2.mp4

so, what could be the problem?

**Comment by MaxMax2016** [comment]
your data contains many speakers? Not opencpop?

**Comment by MaxMax2016** [comment]
muti-speaker version is under development

**Comment by JeffC0628** [comment]
> your data contains many speakers? Not opencpop?

no, I found it is a any2one voice conversion, so my train data contains only one speaker(use biaobei-BZNSYP as train dataset), but my test data has many speakers to test the performance

**Comment by MaxMax2016** [comment]
voice conversion is so different from singing voice conversion; nsf is not very suitable for VC. VC should use quantized f0 or logf0 as input.

**Comment by MaxMax2016** [comment]
it is a good idear to use biaobei-BZNSYP for train. i will try it also @JeffC0628

**Comment by JeffC0628** [comment]
> voice conversion is so different from singing voice conversion; nsf is not very suitable for VC. VC should use quantized f0 or logf0 as input.

this is the key point, I will try the quantized f0 or logf0 as input, thanks for your reply,  appreciate it

**Comment by yygg678** [comment]
> voice conversion is so different from singing voice conversion; nsf is not very suitable for VC. VC should use quantized f0 or logf0 as input.

想问下，对于语音转换， 不用nsf-hifigan 用hifigan好些？所以是基于vits 输入ppg+加量化f0 ---> wav  波形？
