### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by suzhenghang** [PlayVoice/Uni-SVC#18]
1 基于baker数据训练的分支和基于opencpop数据训练的分支主要是加了个pos（https://github.com/PlayVoice/Uni-SVC/blob/main/utils/dataloader.py#L81），这是出于什么考虑呢？
2 如果我有一个目标音色的讲话和唱歌数据，能否一起训练呢？

**Comment by MaxMax2016** [comment]
1，这是一个逐步完善的过程，加入相对位置编码更方便神经网络去学习；当然不加，神经网络也能自己学习到相关信息。
2，这个项目的目的就是为了这样做，只是还没完成。
